Mar 11, 2025 6:19:40 PM com.ztasks.jdbc.runner.JdbcRunner main
SEVERE: Exception occurred
com.exception.ValidationException: An error occurred while processing your request.
	at com.ztasks.jdbc.task.JdbcTask.retrieveFirstNEmployees(JdbcTask.java:66)
	at com.ztasks.jdbc.runner.JdbcRunner.printFirstNEmployees(JdbcRunner.java:143)
	at com.ztasks.jdbc.runner.JdbcRunner.main(JdbcRunner.java:173)
Caused by: java.sql.SQLException: Parameter index out of range (2 > number of parameters, which is 1).
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:81)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:55)
	at com.mysql.cj.jdbc.ClientPreparedStatement.checkBounds(ClientPreparedStatement.java:1482)
	at com.mysql.cj.jdbc.ClientPreparedStatement.getCoreParameterIndex(ClientPreparedStatement.java:1497)
	at com.mysql.cj.jdbc.ClientPreparedStatement.setInt(ClientPreparedStatement.java:1769)
	at com.ztasks.jdbc.task.EmployeeDAO.getEmployees(EmployeeDAO.java:104)
	at com.ztasks.jdbc.task.EmployeeDAO.getEmployees(EmployeeDAO.java:85)
	at com.ztasks.jdbc.task.JdbcTask.retrieveFirstNEmployees(JdbcTask.java:63)
	... 2 more

